name: Build Angular App With Docker

on:
  push:
    branches: [ dev , staging, production]
  pull_request:
    branches: [ dev , staging, production]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quanby-lms:$(date +%s)
